name: My First Github Action
on: [push] # when this action is supposed to run
jobs:
  print-output:
    runs-on: ubuntu-latest
    steps:
      - run: console.log("Hello World!!")
      - run: console.log("Step")
