name: My First Github Action
on: [push] # when this action is supposed to run
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.12.1"
      - run: node -v
